import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import Providers from './providers';
import Header from '@/components/Header';
import ReactScan from '@/components/ReactScan';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
        >
            <body className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col px-2 antialiased`}>
                {process.env.NODE_ENV === 'development' && <ReactScan />}
                <Providers>
                    <Header />
                    <main
                        role="main"
                        className="flex-1"
                    >
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    );
}
